config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  patch "journals/:id", to: "journals#update"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :trips, except: [:destroy] do
    resources :destinations
    resources :journals, only: [:index]
    resources :packages, only: [] do
    member do
        post :set_package
      end
    end
  end
  resources :journals, only: [:show, :update]
  resources :recommendations, only: [:new, :create, :index]
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :package, optional: true
  has_many :packages, dependent: :destroy
  belongs_to :destination

  has_many :journals
  has_many_attached :photos

  def selected_package
    packages.find_by(selected: true) || packages.last
  end

  def duration
    number_of_days = end_date - start_date
    return number_of_days
  end


  enum category: {
    backpacker: 1,
    luxury_traveler: 2,
    adventure_seeker: 3,
    cultural_explorer: 4,
    family_vacationer: 5
  }
  def self.humanized_categories
    {
      backpacker: "Backpacker",
      luxury_traveler: "Luxury Traveller",
      adventure_seeker: "Adventure Seeker",
      cultural_explorer: "Cultural Explorer",
      family_vacationer: "Family Vacationer"
    }
  end

  def generate_packages
    client = OpenAI::Client.new
    chatgpt_response = client.chat(parameters: {
      model: "gpt-4o-mini",
      messages: [{ role: "user", content: "Please generate 1 travel package for  #{self.category} to #{destination.name}
        with a budget of #{budget} from #{start_date} to #{end_date}. The packages must be specific to #{self.category} trips,
        and they must be related to #{destination.name}. Do not include any packages for other categories or destinations.
        Don't mention the dates, category, and total budget at the beginning of your answer.Just the package details. Make the description short"}]
    })
    response_text = chatgpt_response["choices"][0]["message"]["content"]
    # descriptions = response_text.scan(/### Package \d+:.*?(?=\n{2,}### Package \d+:|\z)/m)
    # descriptions = descriptions.map { |desc| desc.sub(/---.*/m, "") }
    # packages = []
    # descriptions.each do |description|
    package = Package.create!(
      name: "#{self.category} package to #{destination.name}",
      description: response_text,
      trip_id: self.id
    )
    package.set_photo(self) if self.photos.attached?
  end

  # def generate_recommendations
  # end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update]

  def index
    @trips = current_user.trips
    @destinations = current_user.destinations # change to current user destinations (has many through)
    @markers = @destinations.geocoded.map do |destination|
      {
        lat: destination.latitude,
        lng: destination.longitude
      }
    end
  end

  def show
    @trip_packages = @trip.packages
    @journals = Journal.with_rich_text_content
    @trip_journals = @trip.journals
    @selected_package = @trip.packages.find_by(selected: true)
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    destination = Destination.find(params[:trip][:destination_id])
    @trip.destination = destination
    @trip.user = current_user
    if @trip.save!
      GeneratePackagesJob.perform_later(@trip)
      @trip.duration.to_i.times do |i|
        @trip.journals.create!(date: @trip.start_date + i, title: "Day #{i + 1}")
      end
      Turbo::StreamsChannel.broadcast_replace_to(
        "trip_#{@trip.id}_packages",
        target: "trip_packages",
        partial: "trips/packages",
        locals: { trip: @trip }
      )
      redirect_to trip_path(@trip)
    else
      render :new, status: :unproccessable_entity
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:start_date, :end_date, :budget, :destination_id, :category, photos: [])
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end

end

app/views/trips/_form.erb
<h1>create your own trip</h1>

<%= simple_form_for(trip) do |f| %>
  <%= f.input :budget %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :category %>
  <%= f.association :destination %>
  <%= f.submit %>
<% end %>

app/views/trips/_packages.html.erb
<% if trip.packages.any? %>
  <div class="trip-package-cards">
    <% trip.packages.each do |package| %>
      <div class="trip-package-card">
        <div class="trip-package-image">
          <%= button_to set_package_trip_package_path(trip, package),
    class: "card-simple-button", id: "choose-package-button", method: :post,
    form: { data: { turbo: false } } do %>
            Choose package
          <% end %>
          <% if package.photo.attached? %>
            <%= cl_image_tag(package.photo.key, alt: "AI-generated image", class:"card-simple-image") %>
          <% else %>
            <%= image_tag('Italy.png', class:"card-simple-image") %>
          <% end %>
        </div>
        <div class="trip-package-details">
          <p><%= clean_and_format_description(package.description) %></p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="spinner">
    <!-- Show your loading GIF or spinner -->
    <%= image_tag('plane_taking_off.gif') %>
    <h4>Generating authentic packages... Please wait!</h4>
  </div>
<% end %>

app/views/trips/_trip_photos_form.html.erb
<%= simple_form_for(trip) do |f| %>
  <%= f.input :photos, as: :file, input_html: {multiple: true}%>
  <%= f.submit "Add photo", class: "card-simple-button" %>
<% end %>

app/views/trips/edit.html.erb
<div class="container">
<%= render "form", trip: @trip%>
</div>

app/views/trips/index.html.erb
<div class="container">
  <h1> Wanderlust awaits </h1>
  <h4>
    Ready for your next adventure? Dive into amazing travel experiences shared by fellow explorers! Whether you crave sun-soaked beaches, exhilarating hikes, or hidden gems off the beaten path, we’ve got the perfect inspiration for you. Discover new destinations, fuel your wanderlust, and start planning your dream trip today!
  </h4>
</div>
<div class="row p-3">
  <div class="col-5 trip-index">
    <!--<div class="">-->
    <% @trips.each do |trip| %>
      <%= link_to trip_path(trip) do  %>
        <div class="card-simple m-2">
          <% if trip.photos.attached?  %>
            <%= cl_image_tag(trip.photos.first.key, class:"card-simple-image")%>
          <% else %>
            <%= image_tag("Italy.png", class:"card-simple-image") %>
          <% end %>
          <div class="card-simple-text">
            <h2><%= trip.destination.name %></h2>
            <div class= "card-simple-details">
            <div class="flex-details">
              <%= image_tag("money.png") %>
              <p>$<%= trip.budget %></p>
            </div>
            <div class="flex-details">
              <%= image_tag("dates.png") %>
              <p> <%= "#{trip.start_date.strftime(" %e %b %y")} - #{trip.end_date.strftime(" %e %b %y")}" %></p>
            </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col-7 map-card">
    <div class="map">
      <div style="width: 100%; height: 600px; border-radius: 15px"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container">
  <%= render "form", trip: @trip%>
</div>

app/views/trips/show.html.erb
<%= turbo_stream_from "trip_#{@trip.id}_packages" %>
<div class="container">
  <h1> Your trip to <%= @trip.destination&.name %> 🗺️ </h1>
  <h5>
    Embracing new challenges and stepping outside of comfort zones. Each moment adds to the adventure and creates lasting memories.
    The journey is just as important as the destination.
  </h5>
</div>
<div id="trip_packages_container">
  <% if @selected_package.present?%>
    <div class="selected-trip-container">
      <div id="selected-package-card" class="row">
        <div class="col-7 d-flex">
          <% if @trip&.photos&.attached? && @trip.photos.any? %>
            <% first_photo = @trip.photos.first %>
            <%= cl_image_tag(first_photo.key, alt: "AI-generated image of the package destination", class: "half-width") %>
          <% else %>
            <%= image_tag("Italy.png", class: "half-width") %>
          <% end %>
          <div class="text-container">
            <% if @selected_package&.description.present? %>
              <p> <%= clean_and_format_description(@selected_package.description) %> </p>
            <% end %>
            <%= simple_form_for(@trip) do |f| %>
              <%= f.input :photos, as: :file, input_html: { multiple: true } %>
              <%= f.submit "Add photo", class: "card-simple-button" %>
            <% end %>
            <%#= simple_form_for(@recommendation) do |f| %>
              <%# <%= f.input :category, as: :select, collection: Recommendation.humanized_categories.keys, include_blank: false, label_method: lambda { |key| Recommendation.humanized_categories[key] }, prompt: "Select Food Type" %>
              <%#= f.submit "Create restuarant recommendations", class: "card-simple-button" %>
              <%# end %>
            </div>
          </div>
          <div id="selected-journal-card" class="col-4 trip-journal-card">
            <div class="text-center mb-5">
              <%= link_to "Journal", trip_journals_path(@trip), class: "card-simple-button" %>
            </div>
            <div class="carousel-journal">
              <% if @trip.journals.first.rich_text_content&.body.present? %>
                <% @trip.journals.each do |journal| %>
                  <% if journal.rich_text_content&.body.present? %>
                    <div class="trip-journal-card journal-card text-center">
                      <%= link_to journal.title, journal_path(journal) %>
                      <div class="journal-text">
                        <%= journal.content %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% else %>
                <p>
                  Now is the time to savor the anticipation, to dream about the sights, sounds, and flavors ahead. But don’t let those fleeting details slip away—capture them. Let your journal be your travel companion, a place to spill your excitement, sketch the landscapes, and write down the little moments that make your adventure uniquely yours.
                  Start your journey before you even step on the plane—begin journaling today!
                </p>
              <% end %>
              <% if @trip.photos.attached? %>
                <div class="space-carousel">
                  <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                      <% @trip.photos.each_with_index do |photo, index| %>
                        <div class="carousel-item <%= 'active' if index.zero? %>">
                          <%= cl_image_tag(photo.key, class: "d-block w-100") %>
                        </div>
                      <% end %>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div id="trip_<%= @trip.id %>">
        <div class="trip-card">
          <div id="trip_packages">
            <%= render "trips/packages", trip: @trip %>
          </div>
        </div>
      </div>
    <% end %>
  </div>