config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  patch "journals/:id", to: "journals#update"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :trips, except: [:destroy] do
    resources :destinations
    resources :journals, only: [:index]
    resources :packages, only: [] do
    member do
        post :set_package
      end
    end
  end
  resources :journals, only: [:show, :update]
  resources :recommendations, only: [:new, :create, :index]
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :trip
  has_rich_text :content
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def index
    @trip = Trip.find(params[:trip_id])
    @journals = @trip.journals
  end

  def show
    @journal = Journal.find(params[:id])
  end

  def update
    @journal = Journal.find(params[:id])
    if @journal.update!(journal_params)
    # No need for app/views/restaurants/update.html.erb
      redirect_to trip_journals_path(@journal.trip)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def create
    @journal = Journal.new(journal_params)
    @journal.save
  end

  private

  def journal_params
    params.require(:journal).permit(:title, :date, :content)
  end
end

app/views/journals/index.html.erb
<div class="selected-trip-heading">
  <%= link_to trip_path(@trip) do  %>
    <h1> Your trip to <%= @trip.destination.name  %> 🗺️ </h1>
  <% end %>
  <div class="container">
    <h5> Embracing new challenges and stepping outside of comfort zones. Each moment adds to the adventure and creates lasting memories.
      The journey is just as important as the destination.
    </h5>
    <%= image_tag('cruise.png', class:'cruise') %>
    <div class="journal-container">
      <% @journals.each do |journal| %>
        <div class="journal-card">
          <%= link_to journal.title, journal_path(journal) %>
          <div class="journal-text">
            <% if journal.content.present? %>
              <%= journal.content %>
            <% else %>
              <p> Add your journal memories here </p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

app/views/journals/show.html.erb
<div class="container lg">
  <div class="journal-entry-card">
    <div class="icon-heading-container">
      <div id="icon">
        <i class="fa-brands fa-fly"></i>
      </div>
      <h2>Journal Entry</h2>
      <div id="icon">
        <i class="fa-brands fa-fly"></i>
      </div>
    </div>
    <% if @journal.content == nil %>
      <h2><%= @journal.title %></h2>
      <p><%= @journal.date %></p>
      <p><%= @journal.content %></p>
    <% else %>
      <%= simple_form_for(@journal) do |f| %>
        <div class="form-inputs">
          <%= f.input :title %>
          <%= f.input :date %>
          <div class="form-inputs mb-4">
            <%= f.rich_text_area :content %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, class:"card-simple-button" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>